jobs:
  - name: ecs-man
    type: manifest
    steps:
      - GET: ecs-nginx
  
  - name: ecs-deploy
    type: ecsDeploy
    steps:
      - GET: ecs-man
      - GET: ecs-cluster

  - name: ecs-deploy-1
    type: ecsDeploy
    options:
      deployMethod: "upgrade"
    steps:
      - GET: ecs-man
      - GET: ecs-cluster
