triggers:
  - name: sn-trigger-1
    type: trigger
    version:
      counter: 43

  - name: sn-tm-trigger
    type: trigger
    version:
      counter: 11

  - name: sn-gke-trigger
    type: trigger
    version:
      counter: 11
