triggers:
  - name: new-tri-trigger
    type: trigger
    pointer:
      counte: 9

  - name: old-tri-trigger
    type: trigger
    pointer:
      counte: 70

  - name: lmon-dcl-trigger
    type: trigger
    pointer:
      counte: 78
