jobs:
  - name: lthu-man-7
    type: manifest
    steps:
      - IN: sn-driftking
      - IN: sn-replicas
      - IN: lthu-trigger-2

  - name: lthu-deploy-2
    type: deploy
    steps:
      - IN: lthu-man-7
      - IN: tripub-cluter
