triggers:
  - name: fl-trigger
    type: trigger
    pointer:
      counter: 11

  - name: flbg-trigger
    type: trigger
    pointer:
      counter: 3

  - name: flsm-trigger
    type: trigger
    pointer:
      counter: 2

  # - name: x-trigger
  #   type: trigger
  #   pointer:
  #     counter: 2
