jobs:
  # - name: sn-q-man-1
  #   type: manifest
  #   steps:
  #     - IN: sn-q-ep
  #     - IN: sn-q-docker-opts-1
  #     - IN: sn-q-trigger-1
  #
  # - name: sn-q-ecs-dep
  #   type: deploy
  #   steps:
  #     - IN: sn-q-man-1
  #     - IN: sn-q-ecs-cluster
  #
  - name: sn-q-tri-man
    type: manifest
    steps:
      - IN: sn-q-dk
      - IN: sn-q-tm-trigger

  - name: sn-q-tri-dep-1
    type: deploy
    steps:
      - IN: sn-q-tri-man
        versionNumber: 1
      - IN: sn-q-tri-cluster

  - name: sn-q-tri-man-2
    type: manifest
    steps:
      - IN: sn-q-ep
      - IN: sn-q-tm-trigger-2

  - name: sn-q-tri-dep-2
    type: deploy
    steps:
      - IN: sn-q-tri-man-2
      - IN: sn-q-tri-cluster

  # - name: sn-q-gke-man
  #   type: manifest
  #   steps:
  #     - IN: sn-q-dk
  #     # - IN: sn-q-docker-opts-1
  #     - IN: sn-q-gke-trigger

  # - name: sn-q-gke-dep
  #   type: deploy
  #   steps:
  #     - IN: sn-q-gke-man
  #     - IN: sn-q-gke-cluster


  - name: sn-q-ddc-man
    type: manifest
    steps:
      - IN: sn-q-ep
      - IN: sn-q-ddc-trigger

  - name: sn-q-ddc-dep
    type: deploy
    steps:
      - IN: sn-q-ddc-man
      - IN: sn-q-ddc-cluster

  - name: sn-q-ecs-man-bg
    type: manifest
    steps:
      - IN: sn-q-myapp3
      - IN: sn-q-do
      - IN: sn-q-ecs-trigger

  - name: sn-q-ecs-deploy-bg
    type: deploy
    steps:
      - IN: sn-q-ecs-man-bg
      - IN: sn-q-ecs-cluster
      - IN: q-lb-loadbalancer1
        applyTo:
          - manifest: sn-q-ecs-man-bg
            image: sn-q-myapp3
            port: 80
