jobs:
  - name: l-th-manifest
    type: manifest
    steps:
      - IN: sn-sn
      - IN: sn-opts
      - IN: l-thursday-trigger
      - TASK: managed

  - name: l-th-deploy
    type: tripubDeploy
    steps:
      - IN: l-th-manifest
      - IN: tripub-cluter
      - TASK: managed
