jobs:
  - name: sn-man
    type: manifest
    steps:
      - GET: sn-nginx
      - GET: sn-trigger
      # - GET: sn-opts
      # - GET: sn-replicas

  - name: loc-gke
    type: gkeDeploy
    steps:
      - GET: sn-man
      - GET: sn-gke

  - name: ecs-man-2
    type: manifest
    steps:
      - GET: sn-sn
      - GET: ecs-trigger
      # - GET: sn-opts
      # - GET: sn-replicas

  - name: loc-ecs-2
    type: ecsDeploy
    steps:
      - GET: ecs-man-2
      - GET: sn-ecs
