triggers:
  - name: sn-q-trigger-1
    type: trigger
    version:
      counter: 43

  - name: sn-q-tm-trigger
    type: trigger
    version:
      counter: 5

  - name: sn-q-tm-trigger-2
    type: trigger
    version:
      counter: 2

  - name: sn-q-ddc-trigger
    type: trigger
    version:
      counter: 2

  - name: sn-q-gke-trigger
    type: trigger
    version:
      counter: 6
