triggers:
  - name: sn-trigger-4
    type: trigger
    version:
      counter: 3

  - name: release-trigger
    type: trigger
    version:
      counter: 4


  - name: deps-trigger
    type: trigger
    version:
      counter: 5

  # - name: runTrigger
  #   type: trigger
  #   pointer:
  #     counter: 5
