triggers:
  - name: l-friday-trigger
    type: trigger
    pointer:
      counter: 35

  - name: l-friday-trigger-xx
    type: trigger
    pointer:
      counter: 35

  - name: l2-trigger
    type: trigger
    pointer:
      counter: 31

  - name: l3-man
    type: manifest
    steps:
      - IN: sn-driftking
      - IN: l3-trigger
