triggers:
  - name: lthu-trigger-2
    type: trigger
    pointer:
      counter: 13

  - name: old-tri-trigger
    type: trigger
    pointer:
      counte: 70

  - name: lmon-dcl-trigger
    type: trigger
    pointer:
      counte: 78
