jobs:
  - name: sn-man-1
    type: manifest
    steps:
      - IN: sn-myapp3-1
      - IN: sn-docker-opts-1
      - IN: sn-trigger-3

  - name: sn-ecsDeploy-7
    type: deploy
    steps:
      - IN: sn-man-1
      - IN: sn-ecs-cluster-1
      # - IN: sn-lb
      #   applyTo:
      #     - manifest: sn-man-1
      #       image: sn-myapp3-1
      #       port: 80
      - TASK: managed
        deployMethod: upgrade
