triggers:
  - name: sn-trigger-4
    type: trigger
    version:
      counter: 14

  - name: release-trigger
    type: trigger
    version:
      counter: 4

  # - name: runTrigger
  #   type: trigger
  #   pointer:
  #     counter: 5
