jobs:
  - name: lmon-tri-man
    type: manifest
    steps:
      - IN: sn-redis
      - IN: lmon-tri-trigger

  - name: lmon-tri-deploy
    type: deploy
    steps:
      - IN: lmon-tri-man
      - IN: tripub-cluter
