jobs:
  - name: sn-man-1
    type: manifest
    steps:
      - IN: sn-myapp3
      - IN: sn-trigger-3
      - TASK: managed

  - name: invalid-man-job-1
    type: manifest
    steps:
      - IN: sn-myapp3

  - name: invalid-release
    type: release
    steps:
      yo: man

  # - name: invalid-rSync
  #   type: rSync
  #   steps:
  #     - IN: sn-myapp3


  # - name: sn-ecs-deploy
  #   type: deploy
  #   steps:
  #     - IN: sn-man-1
  #     - IN: sn-ecs-cluster-1
  #     - TASK: managed
  #       deployMethod: upgrade
  #
  # - name: good-runSh
  #   type: runSh
  #   steps:
  #     - IN: sn-myapp3
  #     - IN: runTrigger
  #     - TASK:
  #         - script: echo "starting ..."
  #         - script: "echo 'versionName=latest' > /build/state/sn-myapp2.env"
  #     - OUT: sn-myapp2

  # - name: fail-runSh
  #   type: runSh
  #   steps:
  #     - IN: script-repo
  #     - IN: runTrigger
  #     - TASK:
  #       - script: /build/IN/script-repo/gitRepo/fail.sh
