##################### GKE Testing starts here
jobs:
  # - name: fl-man
  #   type: manifest
  #   steps:
  #     - GET: sn-nginx
  #     - GET: fl-trigger
  #     - TASK: managed
  #
  # - name: fl-gke
  #   type: gkeDeploy
  #   steps:
  #     - GET: fl-man
  #     - GET: sn-gke
  #     - TASK: managed
  #       deployMethod: upgrade

  - name: sl-1-man
    type: manifest
    steps:
      - GET: sn-sn
      - GET: sl-trigger
      - TASK: managed

  - name: sl-2-man
    type: manifest
    steps:
      - GET: sn-nginx
      - GET: sl-trigger
      - TASK: managed

  - name: slbg-gke
    type: gkeDeploy
    steps:
      - GET: sl-1-man
      - GET: sl-2-man
      - GET: sn-gke
      - TASK: managed
        deployMethod: blueGreen

  # - name: flbg-man
  #   type: manifest
  #   steps:
  #     - GET: sn-nginx
  #     - GET: flbg-trigger
  #     - TASK: managed
  #
  # - name: flbg-gke
  #   type: gkeDeploy
  #   steps:
  #     - GET: flbg-man
  #     - GET: sn-gke
  #     - TASK: managed

  # - name: flsm-man
  #   type: manifest
  #   steps:
  #     - GET: sn-sn
  #     - GET: flsm-trigger
  #     - TASK: managed
  #
  # - name: flsm-gke
  #   type: gkeDeploy
  #   steps:
  #     - GET: flsm-man
  #     - GET: sn-small-gke
  #     - TASK: managed
  #       deployType: blueGreen

  # - name: 1-man
  #   type: manifest
  #   steps:
  #     - GET: sn-sn
  #     - GET: x-trigger
  #
  # - name: 2-man
  #   type: manifest
  #   steps:
  #     - GET: sn-nginx
  #     - GET: x-trigger
  #
  # - name: multi-gke
  #   type: gkeDeploy
  #   options:
  #     deployMethod: blueGreen
  #   steps:
  #     - GET: 1-man
  #     - GET: 2-man
  #     - GET: sn-gke
