triggers:
  - name: lthu-trigger
    type: trigger
    pointer:
      counte: 25

  - name: old-tri-trigger
    type: trigger
    pointer:
      counte: 70

  - name: lmon-dcl-trigger
    type: trigger
    pointer:
      counte: 78
