triggers:
  - name: lmon-tri-trigger
    type: trigger
    pointer:
      counte: 72

  - name: old-tri-trigger
    type: trigger
    pointer:
      counte: 70

  - name: lmon-dcl-trigger
    type: trigger
    pointer:
      counte: 76
