jobs:
  - name: lsa-man-yy
    type: manifest
    steps:
      - IN: sn-driftking
      - IN: sn-opts
      - IN: lsa-trigger-yy

  - name: lsa-deploy-yy
    type: tripubDeploy
    steps:
      - IN: lsa-man-yy
      - IN: tripub-cluter
