triggers:
  - name: sn-q-trigger-1
    type: trigger
    version:
      counter: 43

  - name: sn-q-tm-trigger
    type: trigger
    version:
      counter: 3

  - name: sn-q-ddc-trigger
    type: trigger
    version:
      counter: 1

  - name: sn-q-gke-trigger
    type: trigger
    version:
      counter: 6
