jobs:
  - name: l-mon-common
    type: manifest
    steps:
      - IN: sn-nginx
      - IN: l-mon-trigger
      - TASK: managed

  - name: l-mon-ddc
    type: ddcDeploy
    steps:
      - IN: l-mon-common
      - IN: cluster-ddc
      - TASK: managed

  - name: l-mon-dcl
    type: dclDeploy
    steps:
      - IN: l-mon-common
      - IN: cluster-dcl
      - TASK: managed

  - name: l-mon-ecs
    type: ecsDeploy
    steps:
      - IN: l-mon-common
      - IN: cluster-aws
      - TASK: managed

  - name: l-mon-gke
    type: gkeDeploy
    steps:
      - IN: l-mon-common
      - IN: cluster-gke
      - TASK: managed

  - name: l-mon-tripub
    type: tripubDeploy
    steps:
      - IN: l-mon-common
      - IN: cluster-tripub
      - TASK: managed
