jobs:
  - name: sn-man-1
    type: manifest
    steps:
      - IN: sn-ep
      - IN: sn-docker-opts-1
      - IN: sn-trigger-1

  - name: sn-ecs-deploy-1
    type: deploy
    steps:
      - IN: sn-man-1
      - IN: sn-ddc-cluster
