jobs:
  - name: sn-q-file-man-xxx
    type: manifest
    steps:
      - IN: sn-q-vici-init-js
      - IN: sn-q-params
      - IN: sn-q-file-trigger

  # - name: sn-q-file-man-xxx
  #   type: manifest
  #   steps:
  #     - IN: sn-q-vici-http-js
  #     - IN: sn-q-file-trigger

  - name: sn-q-file-dep-xxx
    type: deploy
    steps:
      - IN: sn-q-file-man-xxx
      - IN: sn-q-params-2
      - IN: sn-q-cluster
      - TASK:
          - script: echo "$MONGO_API_URL"

  # - name: sn-q-chain-file-man
  #   type: manifest
  #   steps:
  #     - IN: sn-q-vici-init-js
  #     - IN: sn-q-chain-trigger

  # - name: sn-q-cluster-deploy-5
  #   type: deploy
  #   steps:
  #     - IN: sn-q-file-man-2
  #     - IN: sn-q-cluster
  #     - TASK:
  #       - script: echo "Hello world !" > abc.txt
  #       - script: ls -l
  #   on_success:
  #     - NOTIFY: slackNotification
  #   on_failure:
  #     - NOTIFY: slackNotification

  # - name: sn-q-chain-deploy
  #   type: deploy
  #   steps:
  #     - IN: sn-q-chain-file-man
  #     - IN: sn-q-cluster

  # - name: sn-q-man-1
  #   type: manifest
  #   steps:
  #     - IN: sn-q-ep
  #     - IN: sn-q-docker-opts-1
  #     - IN: sn-q-trigger-1
  #
  # - name: sn-q-ecs-dep
  #   type: deploy
  #   steps:
  #     - IN: sn-q-man-1
  #     - IN: sn-q-ecs-cluster
  #
  - name: sn-q-tri-man
    type: manifest
    steps:
      - IN: sn-q-dk
      - IN: sn-q-tm-trigger

  - name: sn-q-tri-dep-1
    type: deploy
    steps:
      - IN: sn-q-tri-man
        versionNumber: 1
      - IN: sn-q-tri-cluster

  - name: sn-q-tri-man-2
    type: manifest
    steps:
      - IN: sn-q-ep
      - IN: sn-q-tm-trigger-2

  - name: sn-q-tri-dep-2
    type: deploy
    steps:
      - IN: sn-q-tri-man-2
      - IN: sn-q-tri-cluster

  # - name: sn-q-gke-man
  #   type: manifest
  #   steps:
  #     - IN: sn-q-dk
  #     # - IN: sn-q-docker-opts-1
  #     - IN: sn-q-gke-trigger

  # - name: sn-q-gke-dep
  #   type: deploy
  #   steps:
  #     - IN: sn-q-gke-man
  #     - IN: sn-q-gke-cluster


  - name: sn-q-ddc-man
    type: manifest
    steps:
      - IN: sn-q-ep
      - IN: sn-q-ddc-trigger

  - name: sn-q-ddc-dep
    type: deploy
    steps:
      - IN: sn-q-ddc-man
      - IN: sn-q-ddc-cluster

  - name: sn-q-ecs-man-bg
    type: manifest
    steps:
      - IN: sn-q-myapp3
      - IN: sn-q-do
      - IN: sn-q-ecs-trigger

  - name: sn-q-ecs-deploy-bg
    type: deploy
    steps:
      - IN: sn-q-ecs-man-bg
      - IN: sn-q-ecs-cluster
      - IN: q-lb-loadbalancer1
        applyTo:
          - manifest: sn-q-ecs-man-bg
            image: sn-q-myapp3
            port: 80

  - name: sn-q-runSh
    type: runSh
    steps:
      - IN: sn-q-runSh-trigger
      - TASK:
        - script: ls
        - script: "echo \"versionName=`date +%s`\" > /build/state/sn-q-vici-init-js.env"
      - OUT: sn-q-vici-init-js

  - name: sn-q-mix-a-man
    type: manifest
    steps:
      - IN: sn-q-ep
      - IN: sn-q-mix-a-trigger

  - name: sn-q-mix-b-man
    type: manifest
    steps:
      - IN: sn-q-ep
      - IN: sn-q-mix-b-trigger

  - name: sn-multi-manifest-tri
    type: deploy
    steps:
      - IN: sn-q-mix-a-man
        force: true
      - IN: sn-q-mix-b-man
        force: true
      - IN: sn-q-tri-cluster
      - TASK: managed
        deployOptions:
          - parallel
