##################### GKE Testing starts here
jobs:
  - name: fl-man
    type: manifest
    steps:
      - GET: sn-nginx
      - GET: fl-trigger
      - GET: sn-replicas

  - name: fl-gke
    type: gkeDeploy
    options:
      deployMethod: upgrade
    steps:
      - GET: fl-man
      - GET: sn-gke
