jobs:
  - name: l-sunecs-1-man
    type: manifest
    steps:
      - IN: sn-sn
      - IN: l-sun-trigger
      - TASK: managed

  - name: l-sunecs-2-man
    type: manifest
    steps:
      - IN: sn-nginx
      - IN: l-sun-trigger
      - TASK: managed

  - name: sun-ecs
    type: ecsDeploy
    steps:
      - IN: l-sunecs-1-man
      - IN: l-sunecs-2-man
      - IN: sn-ecs
      - TASK: managed
        deployMethod: upgrade

  - name: lbg-sunecs-1-man
    type: manifest
    steps:
      - IN: sn-nginx
      - IN: lbg-sun-trigger
      - TASK: managed

  - name: lbg-sunecs-2-man
    type: manifest
    steps:
      - IN: sn-sn
      - IN: lbg-sun-trigger
      - TASK: managed

  - name: lbg-sun-ecs
    type: ecsDeploy
    steps:
      - IN: lbg-sunecs-1-man
      - IN: lbg-sunecs-2-man
      - IN: sn-ecs
      - TASK: managed
        deployMethod: blueGreen
