jobs:
  - name: lsat-man-2
    type: manifest
    steps:
      - IN: sn-driftking
      - IN: lsat-trigger

  - name: lsat-tri-deploy-1
    type: deploy
    steps:
      - IN: lsat-man-2
      - IN: tripub-cluter

  # - name: lsat-tri-deploy-2
  #   type: deploy
  #   steps:
  #     - IN: lsat-man-2
  #     - IN: tripub-cluters
