jobs:
  - name: lf-man-yy
    type: manifest
    steps:
      - IN: sn-entrypoint
      # - IN: sn-opts
      - IN: lf-trigger-yy
      - TASK: managed

  - name: lf-deploy-yy
    type: tripubDeploy
    steps:
      - IN: lf-man-yy
      - IN: tripub-cluter
      - TASK: managed
