triggers:
  - name: sn-trigger
    type: trigger
    pointer:
      counter: 11

  - name: ecs-trigger
    type: trigger
    pointer:
      counter: 10

  - name: tri-trigger
    type: trigger
    pointer:
      counter: 2
