triggers:
  - name: sn-trigger-1
    type: trigger
    version:
      counter: 43

  - name: sn-tm-trigger
    type: trigger
    version:
      counter: 12

  - name: sn-ddc-trigger
    type: trigger
    version:
      counter: 2

  - name: sn-gke-trigger
    type: trigger
    version:
      counter: 6
