jobs:
  - name: sn-man-1
    type: manifest
    steps:
      - IN: sn-myapp3
      - IN: sn-trigger-4
      - TASK: managed

  # - name: invalid-rSync
  #   type: rSync
  #   steps:
  #     - IN: sn-myapp3

  # - name: sn-ecs-deploy
  #   type: deploy
  #   steps:
  #     - IN: sn-man-1
  #     - IN: sn-ecs-cluster-1
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: sn-ecs-deploy-1
  #   type: deploy
  #   steps:
  #     - IN: sn-man-1
  #     - IN: sn-ecs-cluster-1
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: sn-ecs-deploy-2
  #   type: deploy
  #   steps:
  #     - IN: sn-man-1
  #     - IN: sn-ecs-cluster-1
  #     - TASK: managed
  #       deployMethod: upgrade

  - name: sn-ecs-deploy-3
    type: deploy
    steps:
      - IN: sn-man-1
      - IN: sn-ecs-cluster-1
      - TASK: managed
        deployMethod: upgrade

  # - name: good-runSh
  #   type: runSh
  #   steps:
  #     - IN: sn-myapp3
  #     - IN: runTrigger
  #     - TASK:
  #         - script: echo "starting ..."
  #         - script: "echo 'versionName=latest' > /build/state/sn-myapp2.env"
  #     - OUT: sn-myapp2

  # - name: fail-runSh
  #   type: runSh
  #   steps:
  #     - IN: script-repo
  #     - IN: runTrigger
  #     - TASK:
  #       - script: /build/IN/script-repo/gitRepo/fail.sh
