triggers:
  - name: l-ddc-trigger
    type: trigger
    pointer:
      counter: 14

  # - name: l-sun-trigger
  #   type: trigger
  #   pointer:
  #     counter: 10
  #
  # - name: lbg-sun-trigger
  #   type: trigger
  #   pointer:
  #     counter: 12
