jobs:
  - name: lthu-man
    type: manifest
    steps:
      - IN: sn-nginx
      - IN: sn-replicas
      - IN: lthu-trigger

  - name: lthu-deploy
    type: deploy
    steps:
      - IN: lthu-man
      - IN: tripub-cluter
