jobs:
  - name: l-fri-manifest
    type: manifest
    steps:
      - IN: sn-driftking
      - IN: sn-opts
      - IN: l-friday-trigger

  - name: l2-man
    type: manifest
    steps:
      - IN: sn-driftking
      - IN: l2-trigger

    - name: l3-man
      type: manifest
      steps:
        - IN: sn-driftking
        - IN: l3-trigger
  # - name: l-fri-deploy
  #   type: tripubDeploy
  #   steps:
  #     - IN: l-fri-manifest
  #     - IN: tripub-cluter
