jobs:
  - name: lsat-man-1
    type: manifest
    steps:
      - IN: sn-driftking
      - IN: lsat-trigger

  - name: lsat-tri-deploy
    type: deploy
    steps:
      - IN: lsat-man
      - IN: tripub-cluter
