jobs:
  - name: sn-man-1
    type: manifest
    steps:
      - IN: sn-ep
      - IN: sn-docker-opts-1
      - IN: sn-trigger-1

  - name: sn-ecs-dep
    type: deploy
    steps:
      - IN: sn-man-1
      - IN: sn-ecs-cluster

  - name: sn-tri-man
    type: manifest
    steps:
      - IN: sn-ep
      - IN: sn-docker-opts-1
      - IN: sn-tm-trigger

  - name: sn-tri-dep
    type: deploy
    steps:
      - IN: sn-tri-man
      - IN: sn-tri-cluster
