##################### GKE Testing starts here
jobs:
  - name: fl-man
    type: manifest
    steps:
      - GET: sn-nginx
      - GET: fl-trigger
      - GET: sn-replicas

  - name: fl-gke
    type: gkeDeploy
    options:
      deployMethod: upgrade
    steps:
      - GET: fl-man
      - GET: sn-gke

  - name: flbg-man
    type: manifest
    steps:
      - GET: sn-nginx
      - GET: flbg-trigger

  - name: flbg-gke
    type: gkeDeploy
    steps:
      - GET: flbg-man
      - GET: sn-gke

  - name: flsm-man
    type: manifest
    steps:
      - GET: sn-sn
      - GET: flsm-trigger

  - name: flsm-gke
    type: gkeDeploy
    steps:
      - GET: flsm-man
      - GET: sn-small-gke

  # - name: 1-man
  #   type: manifest
  #   steps:
  #     - GET: sn-sn
  #     - GET: x-trigger
  #
  # - name: 2-man
  #   type: manifest
  #   steps:
  #     - GET: sn-nginx
  #     - GET: x-trigger
  #
  # - name: multi-gke
  #   type: gkeDeploy
  #   options:
  #     deployMethod: blueGreen
  #   steps:
  #     - GET: 1-man
  #     - GET: 2-man
  #     - GET: sn-gke
