jobs:
  - name: lsat-man-2
    type: manifest
    steps:
      - IN: sn-driftking
      - IN: lsat-trigger

  # - name: lsat-tri-deploy-1
  #   type: deploy
  #   steps:
  #     - IN: lsat-man-2
  #     - IN: tripub-cluter

  # - name: lsat-tri-deploy-2
  #   type: deploy
  #   steps:
  #     - IN: lsat-man-2
  #     - IN: tripub-cluter
  #
  #
  # - name: lsat-tri-deploy-5
  #   type: deploy
  #   steps:
  #     - IN: lsat-man-2
  #     - IN: tripub-cluter

  # - name: lsat-tri-deploy-6
  #   type: deploy
  #   steps:
  #     - IN: lsat-man-2
  #     - IN: tripub-cluter

  # - name: lsat-tri-deploy-7
  #   type: deploy
  #   steps:
  #     - IN: lsat-man-2
  #     - IN: tripub-cluter

  # - name: lsat-tri-deploy-8
  #   type: deploy
  #   steps:
  #     - IN: lsat-man-2
  #     - IN: tripub-cluter

  # - name: lsat-tri-deploy-9
  #   type: deploy
  #   steps:
  #     - IN: lsat-man-2
  #     - IN: tripub-cluter

  # - name: lsat-tri-deploy-10
  #   type: deploy
  #   steps:
  #     - IN: lsat-man-2
  #     - IN: tripub-cluter

  # - name: lsat-tri-deploy-11
  #   type: deploy
  #   steps:
  #     - IN: lsat-man-2
  #     - IN: tripub-cluter

  # - name: lsat-tri-deploy-12
  #   type: deploy
  #   steps:
  #     - IN: lsat-man-2
  #     - IN: tripub-cluter

  - name: lsat-tri-deploy-13
    type: deploy
    steps:
      - IN: lsat-man-2
      - IN: tripub-cluter

  - name: lsat-tri-deploy-14
    type: deploy
    steps:
      - IN: lsat-man-2
      - IN: tripub-cluter

  # - name: lsat-tri-deploy-15
  #   type: deploy
  #   steps:
  #     - IN: lsat-man-2
  #     - IN: tripub-cluter

  # - name: lsat-tri-deploy-16
  #   type: deploy
  #   steps:
  #     - IN: lsat-man-2
  #     - IN: tripub-cluter

  # - name: lsat-tri-deploy-17
  #   type: deploy
  #   steps:
  #     - IN: lsat-man-2
  #     - IN: tripub-cluter

  - name: lsat-tri-deploy-18
    type: deploy
    steps:
      - IN: lsat-man-2
      - IN: tripub-cluter
